set-window-option -g mode-keys vi

bind -n M-R source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"
bind -n M-[ copy-mode

bind -n M-n new-window
bind -n M-L next-window
bind -n M-H previous-window
bind -n M-Q kill-window

bind -n M-\\ split-window -v
bind -n M-Enter split-window -h
bind -n M-q kill-pane
bind -n M-f resize-pane -Z

bind -n M-BSpace clear-history

bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

bind -n C-M-h resize-pane -L 5
bind -n C-M-l resize-pane -R 5
bind -n C-M-k resize-pane -U 5
bind -n C-M-j resize-pane -D 5

bind -n M-p run "xclip -o -selection clipboard | tmux load-buffer - ; tmux paste-buffer"
bind-key -T copy-mode-vi v if-shell -F '#{selection_present}' 'send-keys -X clear-selection' 'send-keys -X begin-selection'
bind-key -T copy-mode-vi y send-keys -X copy-pipe "xclip -selection clipboard -i"
bind-key -T copy-mode-vi Escape send-keys -X cancel
